# Generated by Django 5.1.5 on 2025-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('asistir', models.BooleanField()),
                ('alergia', models.BooleanField()),
                ('comentario', models.TextField(blank=True)),
                ('autobus', models.BooleanField()),
            ],
        ),
    ]
