# Generated by Django 5.1.5 on 2025-11-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitados',
            name='cancion',
            field=models.TextField(blank=True),
        ),
    ]
